name: Daily V-Pulse Tracking

on:
  schedule:
    - cron: '0 1 * * *'  # UTC时间1点（北京时间9点）
  workflow_dispatch:      # 允许手动触发

env:
  TZ: Asia/Shanghai    # 设置时区为中国时区

jobs:
  track:
    # 只在 main 分支上运行
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    # 获取完整历史记录以保留数据
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tracker
      run: |
        echo "开始运行时间: $(date '+%Y-%m-%d %H:%M:%S')"
        python run_daily.py
        echo "结束运行时间: $(date '+%Y-%m-%d %H:%M:%S')"
        
    - name: Commit and push to main
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/
        git commit -m "Update tracking data for $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync data to gh-pages
      run: |
        # 保存当前数据
        cp -r data /tmp/data
        
        # 切换到 gh-pages 分支
        git fetch origin gh-pages
        git checkout gh-pages
        
        # 更新数据
        rm -rf data
        cp -r /tmp/data data
        
        # 提交更改
        git add data/
        git commit -m "Sync data from main branch - $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
